GET https://mwpgwb.m.jd.com/mwp/mobileDispatch?api=7fresh.user.address.getOutThreeLocation&data={%22lon%22:116.5056856,%22lat%22:39.7922905,%22storeId%22:%22%22,%22source%22:1,%22activityId%22:%22%22}&storeId=0&tenantId=1&platformId=1&lat=&lon=&uuid=ozhP942_DmZzMA0gXmj3Ix5-oNu0&client=m&appName=7fresh&callback=__jp0 HTTP/1.1


### 测试7表单
POST https://beta-api.m.jd.com/api/ HTTP/1.1
Content-Type: application/x-www-form-urlencoded
User-Agent: iPhone
origin: https://7freshbe.m.jd.com

appid=SF-H5
&functionId=7fresh_index_newIndex
&body={
  "v":2,"client":"m","appName":"7fresh","platformId":1,"lat":"39.792206","lon":"116.505486","data":"{\"source\":1}","storeId":131229,"tenantId":1,"uuid":"ozhP942_DmZzMA0gXmj3Ix5-oNu0"
}


### 测试json
POST https://web-api.juejin.im/v3/web/wbbr/gmfnkae HTTP/1.1
Content-Type: application/json
Origin: https://juejin.im
X-Agent: Juejin/Web 

{
  "operationName": "",
  "query": "",
  "variables": {
    "platformCode": 1,
    "positionCodes": [6]
  },
  "extensions": {
    "query": {
      "id": "85c0f781f40a7390dd7aedf0b1b35889"
    }
  }
}